### PR TITLE
Upgrade to yew 0.21.0

### PR DESCRIPTION
**Pull request by griffobeid**

### CODE REVIEW

**Review by darioalessandro — APPROVED** [review]
I think that we need to bump the rust version in the rust action

**Comment by darioalessandro** [comment]
zombie mr

**Comment by LucaCappelletti94** [comment]
Hi all! What needs to happen for this PR? Do you guys need help for finishing and shipping it?

**Comment by LucaCappelletti94** [comment]
Marvelous, thanks!

**Pull request merged**
